name: Deploy Flutter to GitHub Pages

# Trigger the workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

# Define a single job to build and deploy the application
jobs:
  build_and_deploy:
    # Use the latest Ubuntu runner for this job
    runs-on: ubuntu-latest

    # Set up permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: write
      pages: write
      id-token: write

    # Specify the steps to be executed
    steps:
      # Step 1: Checkout your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter on the runner
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # You can specify a version if needed, e.g., '3.35.1'

      # Step 3: Get the project dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 4: Build the Flutter web application
      # We use the --base-href option to ensure the app works correctly on GitHub Pages
      - name: Build Flutter web app
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/

      # Step 5: Configure the GitHub Pages deployment
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      # Step 6: Upload the built artifacts to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web'

      # Step 7: Deploy the artifacts to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
