name: Flutter Web Self-Hosted Deployment

on:
  push:
    branches:
      - test-branch

jobs:
  build_and_deploy:
    # This is the key part: it tells GitHub to run this job on your
    # self-hosted runner instead of a default GitHub-hosted runner.
    # Replace 'self-hosted' with any custom labels you've set up.
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'

      - name: Build Flutter Web App
        run: flutter build web --release

      - name: Deploy to Replit
        # The `run` command executes directly on the Replit server.
        run: |
          # Use shell commands to remove old files and copy new ones.
          # The "~" is the home directory of your Replit project.
          echo "Starting deployment to Replit..."
          rm -rf public/*
          cp -r build/web/* public/
          echo "Deployment to Replit completed!"
